version: 2

sources:
  - name: raw
    description: "Raw ingested NFL data from nflverse"
    schema: raw
    loaded_at_field: _ingested_at
    
    tables:
      - name: players
        description: "Master player index with identifiers and biographical data"
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: data
            description: "Raw player data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: rosters
        description: "Seasonal team rosters"
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: data
            description: "Raw roster data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: schedules
        description: "Game schedules by season and week"
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: data
            description: "Raw schedule data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: weekly_player_stats
        description: "Weekly fantasy and statistical lines per player"
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: week
            description: "NFL week number"
            tests:
              - not_null
          - name: data
            description: "Raw weekly stats data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: participation
        description: "Snap counts, routes, and participation per player-week"
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: week
            description: "NFL week number"
            tests:
              - not_null
          - name: data
            description: "Raw participation data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: injuries
        description: "Player injury reports per week"
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: week
            description: "NFL week number"
            tests:
              - not_null
          - name: data
            description: "Raw injury data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null
      
      - name: depth_charts
        description: "Team depth charts per week"
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        columns:
          - name: dataset
            description: "Dataset identifier"
            tests:
              - not_null
          - name: season
            description: "NFL season year"
            tests:
              - not_null
          - name: week
            description: "NFL week number"
            tests:
              - not_null
          - name: data
            description: "Raw depth chart data as JSON"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when data was ingested"
            tests:
              - not_null